### ISSUE TITLE
Safety with comparison with imgui-rs

### ISSUE THREAD

**Issue by NoelJacob** [rodrigorc/easy-imgui-rs#1]
Which is more safe according to you?

**Comment by rodrigorc** [comment]
> Which is more safe according to you?

Well, that is difficult to say, "Safe" means a lot of different things. For example `imgui-rs` is more mature, that for sure, it has been there for about 10 years. `easy-imgui-rs` hasn't a year yet... For that alone, `imgui-rs` feels _safer_.

But that also means that `imgui-rs` has some old patterns, that maybe they are not the best idea... for example, to create a menu in `imgui-rs` you can use `Ui::menu()` that takes a callback, or you can use `Ui::begin_menu()` that returns a token that will close the menu on drop. But as it is widely known now, the "it's safe because it is dropped" pattern is not actually safe, you can reorder the drops, or `std::forget()` the token, and then DearImGui will probably `assert`.
In `easy-imgui-rs` there is only the callback methods, that I think should make the API safer. 

You can certainly make `easy-imgui-rs` assert too, but I think it will be harder to make it so.

Other thing to take into account is that `imgui-rs` still uses DearImgui `1.89.2`, while `easy-imgui-rs` uses the latest `1.90.4`. I will try to always support the latest released version. I think I'll be able to do this because of two main differences between the two:
* Dear ImGui is a C++ library, I use a direct C++ binding, but they use a C++ to C api translator, I think `cimgui`, that may not work 100% of the time.
* My public API is more similar to that of Dear ImGui, that means less work to adapt every new version.

And I guess that using the latest version of Dear ImGui will be _safer_ from a certain point of view...

My (admittedly short) experience with both, is that they are similarly safe. You can make both assert or fail using safe code, but that is just life with C libraries.

My main objective with this new crate was, not to make it safer, but to be able to update to the latest Dear ImGui version easily and to have access to some things that `imgui-rs` didn't have, such as "custom rectangles" in the font atlas, additional callbacks...

Now, I'm not sure I answered your question? Did I?

**Comment by NoelJacob** [comment]
Wow thanks for the long reply. I ment like which has minimal unsafe code blocks. And thanks for creating this library.

**Comment by rodrigorc** [comment]
I think that the "number of unsafe blocks" is not a proper metric here. Both are basically wrappers for the Dear ImGui C++ library, and every single call to the library must have an unsafe block, no matter how trivial it is the work it does.

That metric maybe would be appropriate for a Rust-only library, but for a C/C++ wrapper, you are just counting the interface points.

If you are really worried about safeness in that way, you may consider using a Rust only crate such as `egui`.

But if you use this crate and find anything that you suspect may be unsound or unsafe, please open an issue and we will check it.

**Comment by NoelJacob** [comment]
Thanks for clarifying.
